### PR TITLE
Update About 1-Wire Module

### PR DESCRIPTION
**Pull request by synaptiko**
* fix few typos
* add proper image for the module
* add 1-wire module to the list of hardware to generate "Product related links" section

Note: there is invalid PDF schematics for 1-wire module on the URL: https://github.com/bigclownlabs/bc-hardware/blob/master/out/bc-onewire. It should be https://github.com/bigclownlabs/bc-hardware/tree/master/out/bc-module-1-wire instead but the problem is that this URL generated from `hardware.yml`. Any ideas how to fix it? :-)

### CODE REVIEW

**Comment by synaptiko** [comment]
FYI fixed typos: image

**Comment by hubpav** [comment]
Hi, where do you see this link, please? https://github.com/bigclownlabs/bc-hardware/blob/master/out/bc-onewire

**Comment by synaptiko** [comment]
@hubpav on the bottom of this page: https://www.bigclown.com/doc/hardware/about-1-wire-module/
image

**Comment by hubpav** [comment]
I have just deployed a brand new hardware section with more flexibility on resource specification. I hope you will find it more beautiful too 😄

**Comment by synaptiko** [comment]
That's great, I like it :-)

**Pull request merged**
